### ISSUE TITLE
Handle missing grouping properties

### ISSUE THREAD

**Issue by Operacy** [reminyborg/aggsy#8]
With an array like:

``` javascript
var people = [
  { name: 'Bill', car: 'Toyota' },
  { name: 'Jane', car: 'Lexus' },
  { name: 'Bob'}  // car property missing
]
```

So `aggsy('car()', people)` would return:

``` javascript
{
  'Toyota': [ { name: 'Bill', car: 'Toyota' } ],
  'Lexus': [ { name: 'Jane', car: 'Lexus' } ]
}
```

It would be nice to be able to group items that are missing the grouping property. Maybe by an option (e.g. _missing_). Then `aggsy('car()', { missing: '_leftovers' }, people)` would return:

``` javascript
{
  'Toyota': [ { name: 'Bill', car: 'Toyota' } ],
  'Lexus': [ { name: 'Jane', car: 'Lexus' } ],
  '_leftovers': [ { name: 'Bob'} ]
}
```

**Comment by reminyborg** [comment]
Added test to try this usecase on branch _missing_grouping_properties_

Fun fact that i did not expect: 

``` javascript
var people = [
  { name: 'Bill', car: 'Toyota' },
  { name: 'Jane', car: 'Lexus' },
  { name: 'Bob'}  // car property missing
]
aggsy('car()', people)
```

In aggsy v1.0.0 gives:

``` javascript
{ 
  Lexus: [ { car: 'Lexus', name: 'Jane' } ],
  Toyota: [ { car: 'Toyota', name: 'Bill' } ],
  undefined: [ { name: 'Bob' } ] }
}
```

As long as it is only one undefined deep it works like a charm.
I think for an unintended functionality it is pretty awesome.

I agree with the options `missing` false as default so that the undefined value is filtered away.
And the user can set a missing group name with { missing: '_leftovers' }

We also need to add support for dot notation where all parts of the structure can be undefined like `car.make()`
